import { ExampleCard } from "@/components/ExampleCard";
import { EXAMPLES } from "@/lib";

export const metadata = { title: "Example reports — Pigtail" };

export default function Examples() {
  return (
    <section className="section">
      <h1 className="page-title">Example reports</h1>
      <p className="lead">
        Reports generated by Pigtail that passed its automated publication checks: personal data is
        minimized, sensitive claims are removed or sent to review, and excerpts are kept short.
        Independent analyses based on public sources; Pigtail is not affiliated with the companies and
        projects shown.
      </p>
      <div className="grid3">{EXAMPLES.map((ex) => <ExampleCard key={ex.slug} ex={ex} />)}</div>
      {EXAMPLES.length === 0 && <p className="muted">No reviewed examples yet.</p>}
    </section>
  );
}
