import { ExampleCard } from "@/components/ExampleCard";
import { EXAMPLES } from "@/lib";

export const metadata = { title: "Example reports — Pigtail" };

export default function Examples() {
  return (
    <section className="section">
      <h1 className="page-title">Example reports</h1>
      <p className="lead">
        Reports generated by Pigtail and reviewed before publication. Each one is the same HTML file
        Pigtail writes on your computer, plus the Research Bundle it was drawn from.
      </p>
      <div className="grid3">{EXAMPLES.map((ex) => <ExampleCard key={ex.slug} ex={ex} />)}</div>
      {EXAMPLES.length === 0 && <p className="muted">No reviewed examples yet.</p>}
    </section>
  );
}
