import { ExampleCard } from "@/components/ExampleCard";
import { EXAMPLES, isOss } from "@/lib";

export const metadata = { title: "Example reports — Pigtail" };

const GROUPS = [
  { key: "oss", title: "Open-source projects", badge: "Open source", filter: isOss,
    note: "GitHub repositories, with their exact daily star history next to launches, posts and releases." },
  { key: "product", title: "Products", badge: "Product", filter: (e: (typeof EXAMPLES)[number]) => !isOss(e),
    note: "Product websites. No star history: the story comes from launches, pricing, metrics and interviews." },
];

export default function Examples() {
  return (
    <section className="page">
      <div className="eyebrow">Case files</div>
      <h1>Example reports</h1>
      <p className="lead">
        Reports generated by Pigtail that passed its automated publication checks: personal data is
        minimized, sensitive claims are removed or sent to review, and excerpts are kept short.
        Independent analyses based on public sources; Pigtail is not affiliated with the companies and
        projects shown.
      </p>
      <div className="legend">
        {GROUPS.map((g) => <span key={g.key} className={`kind-badge ${g.key}`}>{g.badge}</span>)}
      </div>
      {GROUPS.map((g) => {
        const items = EXAMPLES.filter(g.filter);
        if (!items.length) return null;
        return (
          <div key={g.key} className="kind-group">
            <div className="kind-group-head"><h2>{g.title}</h2><p>{g.note}</p></div>
            <div className="ex-grid">{items.map((ex) => <ExampleCard key={ex.slug} ex={ex} />)}</div>
          </div>
        );
      })}
      {EXAMPLES.length === 0 && <p className="lead">No examples yet.</p>}
    </section>
  );
}
